language: ruby
dist: trusty
sudo: false
cache: bundler
rvm:
  - 2.4.1
addons:
  apt:
    packages:
      - vim-gtk
branches:
  only:
    - master
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - pip install --user vim-vint
  - vim --version
script:
  - bundle exec rspec
  - vint **/*.vim
