dist: trusty
branches:
  only:
    - master
language: ruby
rvm:
  - 2.4.1
before_install:
  - sudo apt-get install vim-gtk
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - bundle install
  - sudo pip install vim-vint
  - vim --version
script:
  - bundle exec rspec
  - vint **/*.vim
