language: ruby
dist: trusty
sudo: false
cache: bundler
addons:
  apt:
    packages:
      - vim-gtk
branches:
  only:
    - master
before_script:
  - pip install --user https://github.com/blueyed/vint/archive/fix-reqs.zip
  - vim --version
script:
  - vint **/*.vim
