language: ruby
dist: trusty
sudo: false
cache: bundler
rvm:
  - 2.4.1
addons:
  apt:
    packages:
      - vim-gtk
branches:
  only:
    - master
before_script:
  - pip install --user vim-vint
  - vim --version
script:
  - make test
  - vint **/*.vim
