version: 2

common: &common
  working_directory: ~/repo
  docker:
    - image: blueyed/vim-python-pep8-indent-vims-for-test:2@sha256:a7be5f4d07ed361ce3ca78cedd413d67d583f96ab0a59feb512af89052c50172

jobs:
  test:
    <<: *common
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            spec/make-coverage
      - run:
          name: Report coverage
          command: |
            covimerage xml
            codecov -X search gcov pycov -f coverage.xml

  checkqa:
    <<: *common
    steps:
      - checkout
      - run:
          name: Lint
          command: |
            vint **/*.vim

workflows:
  version: 2
  test:
    jobs:
      - test
      - checkqa
