" vint: -ProhibitSetNoCompatible
set nocompatible

filetype plugin on
filetype indent on
syntax on

set noswapfile nobackup

" remove default ~/.vim directories to avoid loading plugins
set runtimepath-=~/.vim
set runtimepath-=~/.vim/after

let sfile = expand('<sfile>')
let plugin_path = fnamemodify(sfile, ':p:h:h')
exe 'set runtimepath^='.plugin_path

if exists('$PYTHON_PEP8_INDENT_TEST_PROFILE_FILE')
  execute 'profile start '.expand('$PYTHON_PEP8_INDENT_TEST_PROFILE_FILE')
  execute 'profile! file '. plugin_path . '/indent/python.vim'
endif
